name: Update counts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Runs every hour
    # - cron: "0 0 * * *" # Runs at 00:00

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Set environment variables
        run: |
          echo "DATE_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Run script
        run: python update_counts.py
        timeout-minutes: 5

      - name: Check for changes
        id: check_changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git checkout main
          git add .
          git commit -m "Update counts file ($DATE_TIME)"

      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git push origin main
